num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))
print(f"Addition: {num1+num2}")
print(f"Substraction: {num1-num2}")
print(f"Multiplication: {num1*num2}")
print(f"Division: {num1/num2}")
print(f"Power:  {num1**num2}")
print(f"Remainder: {num1%num2}")